# how to import and use python library

* 작업디렉토리를 정한다.
* Python 파일 (.py)을 생성해서, 읽고 사용한다.
* import 명령어로 존재하는 Python파일을 (.py) 라이브러리로 불러 사용한다.

In [10]:
import os
mywd=%pwd
mych2wd=os.path.join(mywd,'Ch02')

In [27]:
%cd {mywd}

/home/jsl/Code/git/else/machinelearninginaction


In [30]:
%%writefile myknn.py
from numpy import *
import operator

def createDataSet():
    group = array([[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]]) # trainingSet
    labels = ['A','A','B','B'] # labels
    return group, labels

Writing myknn.py


In [31]:
!dir myknn.py

myknn.py


In [32]:
import myknn
g,l=knn.createDataSet()

In [33]:
print g[:2],l[:5]

[[ 1.   1.1]
 [ 1.   1. ]] ['A', 'A', 'B', 'B']


In [20]:
%cd {mych2wd}

/home/jsl/Code/git/else/machinelearninginaction/Ch02


In [21]:
import kNN

In [22]:
from numpy import *
dataSet = array([[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]])
group = ['A','A','B','B']
inX = [0,0]
k = 3
print dataSet.shape[0]

4


In [26]:
myMat, myVec=kNN.file2matrix('datingTestSet.txt')
print myMat[:5], myVec[:5]

[[  4.09200000e+04   8.32697600e+00   9.53952000e-01]
 [  1.44880000e+04   7.15346900e+00   1.67390400e+00]
 [  2.60520000e+04   1.44187100e+00   8.05124000e-01]
 [  7.51360000e+04   1.31473940e+01   4.28964000e-01]
 [  3.83440000e+04   1.66978800e+00   1.34296000e-01]] [3, 2, 1, 1, 1]
